theme: Just the Docs
title: Testing
author: Jose Antonio Padilla Soler
description: This site contains lessons learned in the testing field. Aims to serve both as an initiation and as a self-reminder. 
